// This file has been autogenerated from a class added in the UI designer.
using System;
using Foundation;
using Okta.Oidc;
using UIKit;

namespace Sample.iOS
{
	public partial class AuthViewController : UIViewController
    {
        public OktaOidc oktaAppAuth;
        private string token => tokenTextView.Text;
        public Action<OktaOidcStateManager> onAuthenticated;


        public AuthViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            HideProgress();
            ClearMessageView();
        }

        partial void Authenticate(UIButton sender)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                ShowMessage("You MUST specify session token to authenticate!");
                return;
            }

            ClearMessageView();
            ShowProgress();
            oktaAppAuth?.AuthenticateWithSessionToken(token, (authStateManager,error) =>
            {
                HideProgress();
                if (error != null)
                {
                    PresentError(error);
                    return;
                }

                onAuthenticated(authStateManager);
                DismissViewController(true,null);
            });
        }

        private void PresentError(NSError error)
        {
            ShowMessage("Error " + error.LocalizedDescription);
        }

        private void ShowMessage(string message)
        {
            messageView.Text = message;
        }

        private void ClearMessageView()
        {
            messageView.Text = null;
        }

        private void ShowProgress()
        {
            progressIndicator.StartAnimating();
            progressOverlay.Hidden = false;
        }

        private void HideProgress()
        {
            progressIndicator.StopAnimating();
            progressOverlay.Hidden = true;
        }
    }
}
