// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Sample.iOS
{
	public partial class AuthViewController : UIViewController
	{
		public AuthViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
